# PDF Pipeline Demo

Notebook de test du pipeline.

In [1]:
from main import df
df.head()

   page  width  height  page_area  image_ratio  image_count  text_ratio  \
0     1  612.0   792.0   484704.0          1.0            1    0.012739
1     2  612.0   792.0   484704.0          1.0            1    0.012203
2     3  612.0   792.0   484704.0          1.0            1    0.011784
3     4  612.0   792.0   484704.0          1.0            1    0.012739
4     5  612.0   792.0   484704.0          1.0            1    0.012203

   block_count   density  native_chars  native_words  native_score  \
0            9  0.000019           332            46      0.791519
1            9  0.000019           320            44      0.805148
2            9  0.000019           305            41      0.815856
3            9  0.000019           332            46      0.791519
4            9  0.000019           320            44      0.805148

   repetition_score page_type  processing_time  qa_valid qa_flags  \
0          0.888554      scan         0.033587      True       []
1          0.884375      scan         0.021183      True       []
2          0.895082      scan         0.022361      True       []
3          0.888554      scan         0.021503      True       []
4          0.884375      scan         0.021492      True       []

                                                text
0  Monsieur/Madame: CISSÉ Hamidou\nNuméro de poli...
1  Assuré: FOFANA Djeneba\nDate de naissance: 21/...
2  Assuré: OUATTARA Ladji\nContrat: POL-2022-1563...
3  Monsieur/Madame: CISSÉ Hamidou\nNuméro de poli...
4  Assuré: FOFANA Djeneba\nDate de naissance: 21/...

,page,width,height,page_area,image_ratio,image_count,text_ratio,block_count,density,native_chars,native_words,native_score,repetition_score,page_type,processing_time,qa_valid,qa_flags,text
0,1,612.0,792.0,484704.0,1.0,1,0.012739,9,0.000019,332,46,0.791519,0.888554,scan,0.033587,True,[],Monsieur/Madame: CISSÉ Hamidou\nNuméro de poli...
1,2,612.0,792.0,484704.0,1.0,1,0.012203,9,0.000019,320,44,0.805148,0.884375,scan,0.021183,True,[],Assuré: FOFANA Djeneba\nDate de naissance: 21/...
2,3,612.0,792.0,484704.0,1.0,1,0.011784,9,0.000019,305,41,0.815856,0.895082,scan,0.022361,True,[],Assuré: OUATTARA Ladji\nContrat: POL-2022-1563...
3,4,612.0,792.0,484704.0,1.0,1,0.012739,9,0.000019,332,46,0.791519,0.888554,scan,0.021503,True,[],Monsieur/Madame: CISSÉ Hamidou\nNuméro de poli...
4,5,612.0,792.0,484704.0,1.0,1,0.012203,9,0.000019,320,44,0.805148,0.884375,scan,0.021492,True,[],Assuré: FOFANA Djeneba\nDate de naissance: 21/...

In [2]:
df[['page', 'page_type', 'image_ratio', 'text_ratio']]

    page page_type  image_ratio  text_ratio
0      1      scan          1.0    0.012739
1      2      scan          1.0    0.012203
2      3      scan          1.0    0.011784
3      4      scan          1.0    0.012739
4      5      scan          1.0    0.012203
5      6      scan          1.0    0.011784
6      7      scan          1.0    0.012739
7      8      scan          1.0    0.012203
8      9      scan          1.0    0.011784
9     10      scan          1.0    0.012739
10    11      scan          1.0    0.012203
11    12      scan          1.0    0.011784
12    13      scan          1.0    0.012739
13    14      scan          1.0    0.012203
14    15      scan          1.0    0.011784
15    16      scan          1.0    0.012739
16    17      scan          1.0    0.012203
17    18      scan          1.0    0.011784
18    19      scan          1.0    0.012739
19    20      scan          1.0    0.012203
20    21      scan          1.0    0.011784

In [3]:
df[df['qa_valid'] == False]

Empty DataFrame
Columns: [page, width, height, page_area, image_ratio, image_count, text_ratio, block_count, density, native_chars, native_words, native_score, repetition_score, page_type, processing_time, qa_valid, qa_flags, text]
Index: []